

name: Daily backup

on:
  schedule:
    - cron: '15 9 * * *'
 

jobs:
  build:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3
      - name: Login into azure account
        shell: pwsh
        run: |
         cd /home/azureuser
         $tenantId = "9d68da93-1f22-4f6c-9e91-aa61811bc7b0"
         $appId = "e9fa51dc-d852-4247-8f77-e5b923743cff"
         $password = "bRq8Q~VZ9gs.J5ufsTMbqr8b4wx5wJeUQ.9Slc68"
         sleep 2s
         $securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
         sleep 2s
         $credential = New-Object -TypeName PSCredential -ArgumentList $appId, $securePassword
         sleep 2s
         Connect-AzAccount -ServicePrincipal -Tenant $tenantId -Credential $credential
         sleep 2s
         Get-AzContext
         cron: |
            '20 9 * * *'
         
      - name: Apim backup
        shell: pwsh
        run: |
          $storageAccount = Get-AzStorageAccount -ResourceGroupName "etpxapim-rg" -Name "restoreapiminstances"
          Backup-AzApiManagement -ResourceGroupName "etpxapim-rg" -Name "thbs-apim-2" -StorageContext $storageAccount.Context -TargetContainerName "apim-backup-github" -TargetBlobName "apim-github-backup"



      
