

name: CI

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3

      - name: creating resource group
        run: az group create --name "etpxapimdata" --location "eastus2"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
