

name: CI

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3

      - name: Apim backup
        run: |
          pwsh
          Backup-AzApiManagement -ResourceGroupName "etpxapim-rg" -Name "thbs-apim-2" -StorageContext $storageAccount.Context -TargetContainerName "apim-backup-github" -TargetBlobName "apim-github-backup"



      
