

name: CI

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3

      - name: creating storage account
        run: $storageAccount = New-AzStorageAccount -ResourceGroupName "Ubuntuvm-RG" -Name "apimstorage1" -SkuName Standard_LRS -Location "eastus"


      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
